- hosts: localhost
  connection: local
  become: true
  become_ask_pass=true
  pre_tasks:
  - name: Update Repository
    package:
      update_cache: yes
      changed_when: false

  - name: Upgrade Distro (Debian - Ubuntu)
    package:
      upgrade: dist
    when: ansible_distribution in ["Debian", "Ubuntu"]

#  tasks:
#    - 
#      include: tasks/packages.yml
       # tasks/bash.yml

